# Generated by Django 2.2 on 2021-05-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj2_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('network', models.CharField(max_length=55)),
                ('release_date', models.DateTimeField()),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
