# Generated by Django 2.2 on 2021-05-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj2_app', '0002_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
